# Generated by Django 4.2.7 on 2023-11-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_founder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Info',
        ),
    ]
